export const mockRooms = [
  {
    id: "r1",
    name: "Ruang Rapat Eksekutif A",
    building: "Gedung IKN Tower",
    floor: "Lantai 8",
    capacity: { boardroom: 16 },
    facilities: { tv: 2, projector: 1, videoConference: 1, soundSystem: 1, whiteboard: 2, outlet: 12 },
    layouts: ["Boardroom", "U-Shape"],
    status: "active",
    approvalType: "manual",
    operationalHours: { start: "07:00", end: "18:00" },
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&q=80",
    adminName: "Ahmad Fauzi",
    description: "Ruang rapat premium untuk rapat eksekutif dan tamu VVIP.",
  },
  {
    id: "r2",
    name: "Ruang Diskusi Inovasi",
    building: "Gedung IKN Tower",
    floor: "Lantai 5",
    capacity: { classroom: 30, uShape: 20 },
    facilities: { tv: 1, projector: 2, videoConference: 1, soundSystem: 1, whiteboard: 3, outlet: 20 },
    layouts: ["Classroom", "U-Shape", "Theater"],
    status: "active",
    approvalType: "instant",
    operationalHours: { start: "08:00", end: "17:00" },
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&q=80",
    adminName: "Sari Dewi",
    description: "Ruang kolaborasi untuk sesi brainstorming dan workshop tim.",
  },
  {
    id: "r3",
    name: "Aula Serbaguna Nusantara",
    building: "Gedung Serba Guna",
    floor: "Lantai 1",
    capacity: { theater: 200, standing: 300 },
    facilities: { tv: 4, projector: 3, videoConference: 2, soundSystem: 4, whiteboard: 1, outlet: 40 },
    layouts: ["Theater", "Standing Setup", "Classroom"],
    status: "active",
    approvalType: "manual",
    operationalHours: null,
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=400&q=80",
    adminName: "Bima Pradana",
    description: "Aula besar untuk acara skala besar, seminar, dan pelantikan.",
  },
  {
    id: "r4",
    name: "Ruang Focus Work 01",
    building: "Gedung Teknologi",
    floor: "Lantai 3",
    capacity: { boardroom: 8 },
    facilities: { tv: 1, projector: 0, videoConference: 0, soundSystem: 0, whiteboard: 1, outlet: 8 },
    layouts: ["Boardroom"],
    status: "active",
    approvalType: "instant",
    operationalHours: { start: "07:00", end: "20:00" },
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&q=80",
    adminName: "Rina Kusuma",
    description: "Ruang kecil untuk meeting tim kecil dan sesi focus work.",
  },
  {
    id: "r5",
    name: "Ruang Pelatihan Digital",
    building: "Gedung Teknologi",
    floor: "Lantai 2",
    capacity: { classroom: 40 },
    facilities: { tv: 2, projector: 2, videoConference: 1, soundSystem: 2, whiteboard: 2, outlet: 40 },
    layouts: ["Classroom"],
    status: "active",
    approvalType: "instant",
    operationalHours: { start: "08:00", end: "16:00" },
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=400&q=80",
    adminName: "Rina Kusuma",
    description: "Ruang pelatihan lengkap dengan perangkat teknologi terkini.",
  },
  {
    id: "r6",
    name: "Lounge Kreatif B2",
    building: "Gedung IKN Tower",
    floor: "Lantai 2",
    capacity: { standing: 50, boardroom: 10 },
    facilities: { tv: 1, projector: 0, videoConference: 0, soundSystem: 1, whiteboard: 2, outlet: 16 },
    layouts: ["Standing Setup", "Boardroom"],
    status: "inactive",
    approvalType: "instant",
    operationalHours: { start: "09:00", end: "17:00" },
    image: "https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=400&q=80",
    adminName: "Ahmad Fauzi",
    description: "Ruang santai kreatif. Saat ini dalam renovasi.",
  },
];

export const mockBookings = [
  {
    id: "b1",
    roomId: "r1",
    roomName: "Ruang Rapat Eksekutif A",
    building: "Gedung IKN Tower",
    floor: "Lantai 8",
    date: "2025-05-20",
    startTime: "09:00",
    endTime: "11:00",
    agenda: "Rapat Koordinasi Anggaran Q2",
    participants: 12,
    status: "confirmed",
    userName: "Budi Santoso",
    userId: "u1",
  },
  {
    id: "b2",
    roomId: "r2",
    roomName: "Ruang Diskusi Inovasi",
    building: "Gedung IKN Tower",
    floor: "Lantai 5",
    date: "2025-05-20",
    startTime: "13:00",
    endTime: "15:00",
    agenda: "Workshop Digital Transformation",
    participants: 25,
    status: "confirmed",
    userName: "Budi Santoso",
    userId: "u1",
  },
  {
    id: "b3",
    roomId: "r1",
    roomName: "Ruang Rapat Eksekutif A",
    building: "Gedung IKN Tower",
    floor: "Lantai 8",
    date: "2025-05-21",
    startTime: "10:00",
    endTime: "12:00",
    agenda: "Presentasi Laporan Tahunan",
    participants: 14,
    status: "pending",
    userName: "Dewi Rahayu",
    userId: "u2",
  },
  {
    id: "b4",
    roomId: "r3",
    roomName: "Aula Serbaguna Nusantara",
    building: "Gedung Serba Guna",
    floor: "Lantai 1",
    date: "2025-05-22",
    startTime: "08:00",
    endTime: "17:00",
    agenda: "Seminar Nasional SPBE",
    participants: 180,
    status: "pending",
    userName: "Ahmad Fauzi",
    userId: "u3",
  },
  {
    id: "b5",
    roomId: "r4",
    roomName: "Ruang Focus Work 01",
    building: "Gedung Teknologi",
    floor: "Lantai 3",
    date: "2025-05-18",
    startTime: "14:00",
    endTime: "16:00",
    agenda: "Review Kode Aplikasi",
    participants: 5,
    status: "ongoing",
    userName: "Budi Santoso",
    userId: "u1",
  },
  {
    id: "b6",
    roomId: "r2",
    roomName: "Ruang Diskusi Inovasi",
    building: "Gedung IKN Tower",
    floor: "Lantai 5",
    date: "2025-05-10",
    startTime: "09:00",
    endTime: "11:00",
    agenda: "Sprint Planning",
    participants: 8,
    status: "completed",
    userName: "Budi Santoso",
    userId: "u1",
  },
  {
    id: "b7",
    roomId: "r1",
    roomName: "Ruang Rapat Eksekutif A",
    building: "Gedung IKN Tower",
    floor: "Lantai 8",
    date: "2025-05-12",
    startTime: "13:00",
    endTime: "15:00",
    agenda: "Rapat Direksi Bulanan",
    participants: 10,
    status: "cancelled",
    userName: "Sari Dewi",
    userId: "u4",
  },
];

export const mockUsers = [
  { id: "u1", name: "Budi Santoso", email: "budi.santoso@oikn.go.id", role: "user", status: "active", joinDate: "2024-01-15" },
  { id: "u2", name: "Dewi Rahayu", email: "dewi.rahayu@oikn.go.id", role: "user", status: "active", joinDate: "2024-02-10" },
  { id: "u3", name: "Ahmad Fauzi", email: "ahmad.fauzi@oikn.go.id", role: "admin", status: "active", joinDate: "2023-11-20", assignedRooms: ["r1", "r6"] },
  { id: "u4", name: "Sari Dewi", email: "sari.dewi@oikn.go.id", role: "admin", status: "active", joinDate: "2023-12-05", assignedRooms: ["r2"] },
  { id: "u5", name: "Bima Pradana", email: "bima.pradana@oikn.go.id", role: "admin", status: "active", joinDate: "2024-01-08", assignedRooms: ["r3"] },
  { id: "u6", name: "Rina Kusuma", email: "rina.kusuma@oikn.go.id", role: "admin", status: "active", joinDate: "2024-03-15", assignedRooms: ["r4", "r5"] },
  { id: "u7", name: "Dimas Pratama", email: "dimas.pratama@oikn.go.id", role: "user", status: "inactive", joinDate: "2024-04-01" },
  { id: "u8", name: "Admin Sistem IKNOW", email: "api-iknow@system.oikn.go.id", role: "api", status: "active", joinDate: "2024-01-01" },
];

export const mockAuditLogs = [
  { id: "al1", timestamp: "2025-05-18 14:32:15", actor: "Ahmad Fauzi (Admin)", action: "FORCE_CANCEL", resource: "Booking #B-0234 - Ruang Rapat Eksekutif A", ip: "10.0.1.45", detail: "Alasan: Persiapan kunjungan tamu negara mendadak" },
  { id: "al2", timestamp: "2025-05-18 13:10:08", actor: "Super Admin", action: "UPDATE_POLICY", resource: "Kebijakan Global - Batas durasi booking", ip: "10.0.0.1", detail: "Perubahan: 4 jam → 6 jam per booking" },
  { id: "al3", timestamp: "2025-05-18 11:45:22", actor: "Sari Dewi (Admin)", action: "APPROVE_BOOKING", resource: "Booking #B-0231 - Ruang Diskusi Inovasi", ip: "10.0.2.33", detail: "Disetujui oleh Admin Ruangan" },
  { id: "al4", timestamp: "2025-05-18 10:02:56", actor: "Super Admin", action: "CREATE_ROOM", resource: "Ruang Focus Work 02 (Draft)", ip: "10.0.0.1", detail: "Ruangan baru ditambahkan ke lantai 3 Gedung Teknologi" },
  { id: "al5", timestamp: "2025-05-17 16:30:11", actor: "API: IKNOW System", action: "CREATE_BOOKING", resource: "Booking #B-0230 via API - Ruang Diskusi Inovasi", ip: "172.16.5.20", detail: "Booking remote dari aplikasi IKNOW" },
  { id: "al6", timestamp: "2025-05-17 14:15:44", actor: "Super Admin", action: "REVOKE_TOKEN", resource: "API Token: client_test_123 (Read-Only)", ip: "10.0.0.1", detail: "Token dicabut karena anomali akses" },
  { id: "al7", timestamp: "2025-05-17 09:22:33", actor: "Bima Pradana (Admin)", action: "UPDATE_ROOM", resource: "Aula Serbaguna Nusantara", ip: "10.0.3.55", detail: "Kapasitas theater: 150 → 200 orang" },
];

export const mockApiTokens = [
  { id: "t1", name: "IKNOW Application", clientId: "client_iknow_prod", access: "Read-Write", status: "active", lastUsed: "2025-05-18 13:45", requests: 1248 },
  { id: "t2", name: "Dashboard Monitoring", clientId: "client_dashboard_01", access: "Read-Only", status: "active", lastUsed: "2025-05-18 14:10", requests: 5621 },
  { id: "t3", name: "Test Integration", clientId: "client_test_123", access: "Read-Only", status: "revoked", lastUsed: "2025-05-17 11:30", requests: 42 },
];

export const timeSlots = Array.from({ length: 48 }, (_, i) => {
  const h = Math.floor(i / 2).toString().padStart(2, "0");
  const m = (i % 2 === 0) ? "00" : "30";
  return `${h}:${m}`;
});

export const weekDays = [
  { label: "Sen", date: "19 Mei", full: "Senin, 19 Mei 2025" },
  { label: "Sel", date: "20 Mei", full: "Selasa, 20 Mei 2025" },
  { label: "Rab", date: "21 Mei", full: "Rabu, 21 Mei 2025" },
  { label: "Kam", date: "22 Mei", full: "Kamis, 22 Mei 2025" },
  { label: "Jum", date: "23 Mei", full: "Jumat, 23 Mei 2025" },
];

export const calendarBookings: Record<string, { roomId: string; start: string; end: string; label: string; userId: string }[]> = {
  "2025-05-19_r1": [{ roomId: "r1", start: "09:00", end: "11:00", label: "Rapat Koordinasi", userId: "u3" }],
  "2025-05-19_r2": [{ roomId: "r2", start: "13:00", end: "15:30", label: "Workshop Digital", userId: "u1" }],
  "2025-05-20_r1": [{ roomId: "r1", start: "10:00", end: "12:00", label: "Laporan Tahunan", userId: "u2" }, { roomId: "r1", start: "14:00", end: "16:00", label: "Rapat Direksi", userId: "u3" }],
  "2025-05-20_r2": [{ roomId: "r2", start: "09:00", end: "10:00", label: "Sprint Planning", userId: "u1" }],
  "2025-05-20_r3": [{ roomId: "r3", start: "08:00", end: "17:00", label: "Seminar SPBE", userId: "u3" }],
  "2025-05-21_r4": [{ roomId: "r4", start: "10:00", end: "11:00", label: "Code Review", userId: "u1" }],
  "2025-05-22_r2": [{ roomId: "r2", start: "08:00", end: "10:00", label: "Onboarding", userId: "u4" }, { roomId: "r2", start: "13:00", end: "16:00", label: "Training SDM", userId: "u2" }],
  "2025-05-22_r5": [{ roomId: "r5", start: "09:00", end: "12:00", label: "Pelatihan Digital", userId: "u4" }],
  "2025-05-23_r1": [{ roomId: "r1", start: "14:00", end: "16:00", label: "Board Meeting", userId: "u3" }],
};
